home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.homepage, name='home'),
    path('news/', views.news, name='news'),
    path('adt/', views.adt, name='adt'),
    path('readers/', views.readers, name='readers'),
    path('catalog/', views.catalog, name='catalog'),
    path('structure/', views.structure, name='structure'),
    path('books/', views.books, name='books'),
    path('search', views.search, name='search'),
    path('photo/', views.photo, name='photo'),
    path('video/', views.video, name='video'),
    path('magazine/', views.magazine, name='magazine'),
    path('photo_detail/<int:photo_id>/', views.photo_detail, name='photo_detail'),
    path('search/<slug:category_slug>/', views.list_category, name='list-category'),

    path("<str:language>", views.set_language, name="set-language"),
]

library/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]+i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('home.urls')),
    #path('libraries/', include('forlibraries.urls')),
    prefix_default_language=False,
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/models.py
from django.db import models
from django.urls import reverse
from embed_video.fields import EmbedVideoField


# Create your models here.

class News(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    text = models.TextField(verbose_name='Текст')
    image = models.ImageField(null=True, blank=True, verbose_name='Картинки')
    create_date = models.DateTimeField(auto_now=True, verbose_name='Дата')
    news_view = models.IntegerField(default=0)

    class Meta:
        ordering = ('-id',)
        verbose_name = 'Новости'
        verbose_name_plural = 'Новости'

    def __str__(self):
        return f'{self.title} - {self.create_date}'


class Ads(models.Model):
    title = models.CharField(max_length=200, blank=True, null=True, verbose_name='Заголовок')
    text = models.TextField()
    create_date = models.DateTimeField(auto_now=True, verbose_name='Дата')

    class Meta:
        ordering = ('-id',)
        verbose_name = 'Обявление'
        verbose_name_plural = 'Обявление'

    def __str__(self):
        return self.title


class About(models.Model):
    title = models.CharField(max_length=200, null=True, blank=True)
    info = models.TextField()

    class Meta:
        verbose_name = 'О библиотеки'
        verbose_name_plural = 'О библиотеки'

    def __str__(self):
        return self.title

class History(models.Model):
    text = models.TextField()

    class Meta:
        verbose_name = 'История'
        verbose_name_plural = 'История'

    def __str__(self):
        return str(self.id)


class Structure(models.Model):
    director = models.CharField(max_length=200, null=True, blank=True)
    director_info = models.TextField()
    d_img = models.ImageField(upload_to='avatars/', null=True, blank=True, default='avatars/default.png',
                              verbose_name='Картинки')
    ibo = models.CharField(max_length=200, null=True, blank=True)
    ibo_info = models.TextField()
    ibo_img = models.ImageField(upload_to='avatars/', null=True, blank=True, default='avatars/default.png',
                                verbose_name='Картинки')
    e_res = models.CharField(max_length=200, blank=True)
    e_res_info = models.TextField(blank=True)
    e_res_img = models.ImageField(upload_to='avatars/', blank=True, default='avatars/default.png',
                                  verbose_name='Картинки')

    def __str__(self):
        return f'{self.director} - {self.ibo}'


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        verbose_name_plural = 'Категория'
        ordering = ('-id',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('list-category', args=[self.slug])


class Book(models.Model):
    title = models.CharField(max_length=100, verbose_name='заголовок')
    slug = models.SlugField(max_length=100, verbose_name='слаг')
    author = models.CharField(max_length=100, verbose_name='автор')
    year = models.CharField(max_length=100, verbose_name='год')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    pdf = models.FileField(upload_to='book/pdfs/')
    photo = models.ImageField(upload_to='book/photos/', null=True, blank=True)
    recommended_books = models.BooleanField(default=False, verbose_name='рекомендовано')
    top_books = models.BooleanField(default=False, verbose_name='топ')
    business_books = models.BooleanField(default=False, verbose_name='бизнес')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Книги"
        verbose_name_plural = "Книги"
        ordering = ['-id']

    def get_absolute_url(self):
        return reverse('books', args=[self.slug])


class Photo(models.Model):
    title = models.CharField(max_length=200, blank=True, null=True, verbose_name='Заголовок')
    photo_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Картинки'
        verbose_name_plural = 'Картинки'

    def __str__(self):
        return self.title


class PostImage(models.Model):
    post = models.ForeignKey(Photo, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='img/')


class Newspaper(models.Model):
    number = models.IntegerField(null=True, blank=True)
    title = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name = 'Газета'
        verbose_name_plural = 'Газета'
        ordering = ('id',)

class Readers(models.Model):
    text = models.TextField()

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = 'Читатель'
        verbose_name_plural = 'Читатель'


class Video(models.Model):
    title = models.CharField(max_length=100)
    added = models.DateTimeField(auto_now=True)
    url = EmbedVideoField()

    def __str__(self):
        return str(self.title)

    class Meta:
        ordering = ['-added']
        verbose_name = "Видео"
        verbose_name_plural = "Видео"

class Catalog(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()

    def __str__(self):
        return str(self.title)    

home/views.py
from django.db.models import Q
from django.shortcuts import render
from .models import *
from django.shortcuts import get_object_or_404


#multilanguage
from urllib.parse import urlparse
from django.conf import settings
from django.http import HttpResponseRedirect
from django.urls.base import resolve, reverse
from django.urls.exceptions import Resolver404
from django.utils import translation


def set_language(request, language):
    for lang, _ in settings.LANGUAGES:
        translation.activate(lang)
        try:
            view = resolve(urlparse(request.META.get("HTTP_REFERER")).path)
        except Resolver404:
            view = None
        if view:
            break
    if view:
        translation.activate(language)
        next_url = reverse(view.url_name, args=view.args, kwargs=view.kwargs)
        response = HttpResponseRedirect(next_url)
        response.set_cookie(settings.LANGUAGE_COOKIE_NAME, language)
    else:
        response = HttpResponseRedirect("/")
    return response

# multilanguage code end

# Create your views here.
def homepage(request):
    books = Book.objects.all().order_by('-id')[0:5]
    news = News.objects.all().order_by('-create_date')[0:3]
    adt = Ads.objects.all().order_by('-id')[0:2]
    structure = Structure.objects.all()
    about = About.objects.all()
    history = History.objects.filter(id=1)
    history1 = History.objects.filter(id=2)
    videos = Video.objects.all()
    context = {'news': news,  'adt': adt, 'structure': structure,
                'about': about, 'books': books, 'videos': videos,
                'history': history, 'history1': history1}
    return render(request, 'home.html', context)


def news(request):
    news = News.objects.all()

    contex = {'news': news}
    return render(request, 'news.html', contex)


def adt(request):
    adt = Ads.objects.all()
    contex = {'adt': adt}
    return render(request, 'adt.html', contex)


def readers(request):
    newspapers = Newspaper.objects.all()
    readers = Readers.objects.all()
    context = {'newspapers': newspapers, 'readers': readers}
    return render(request, 'readers.html', context) 


def catalog(request):
    b_catalog = Catalog.objects.filter(id=1)
    catalog = Catalog.objects.filter(id=2)
    el_catalog = Catalog.objects.filter(id=3)
    context = {'b_catalog': b_catalog,'catalog': catalog, 'el_catalog': el_catalog}
    return render(request, 'catalog.html', context)


def structure(request):
    structure = Structure.objects.all()
    context = {'structure': structure}
    return render(request, 'structure.html', context)


def categories(request):
    categories = Category.objects.all().order_by('id')[0:12]
    categories1 = Category.objects.all().order_by('id')[12:23]
    categories2 = Category.objects.all().order_by('id')[23:43]

    return {'categories': categories, 'categories1': categories1, 'categories2': categories2}


def list_category(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    books = Book.objects.filter(category=category)
    return render(request, 'list-category.html', {'category': category, 'books': books})


def books(request):
    books = Book.objects.all()
    context = {'books': books}
    return render(request, 'books.html', context)


def search(request):
    search = request.GET.get('q', '').lower()

    if search:
        books = Book.objects.filter(
            Q(title__icontains=search) |
            Q(author__icontains=search) |
            Q(category__name__icontains=search)
        )
    else:
        books = Book.objects.all().order_by('-id')
    return render(request, 'books.html', {"books": books})


def photo(request):
    photos = Photo.objects.all()
    return render(request, 'photo.html', {'photos': photos})


def photo_detail(request, photo_id):
    photo = get_object_or_404(Photo, id=photo_id)

    return render(request, 'single_photo.html', {'photo': photo})



def video(request):
    return render(request, 'video.html')

def magazine(request):
    return render(request, 'magazine.html')

templates/adt.html
{% extends 'index.html' %}
{% load static %}
{% load i18n %}

{% block content %}

{% include 'navbar.html' %}





<body class="editor_false  lang_ru     not_ie">

    <div id="wrapper" class="" style="padding-top: 88px;">

        <div class="adt">
            <div class="structure_container">
                <h1 class="structure_title">{% trans 'Объявление' %}</h1>
                <div class="adt_content">

                    {% for a in adt %}
                    <div class="adt_box">
                        <div class="adt_text">
                            <p>{{ a.create_date|date:"Y-m-d"}}</p>
                            <h1>{{a.title}}</h1>
                            <p>{{ a.text }}</p> <br>
                            
                            
                        </div> 
                    </div>
                    {% endfor %}
                
                </div>
                
            </div>
        </div>

    </div>

</body>


{% endblock content %}

templates/books.html
{% extends 'index.html' %}
{% load static %}
{% load i18n %}

{% block content %}

{% include 'navbar.html' %}

python manage.py runserver
<body class="editor_false  lang_ru  not_ie">

	<div class="books_item">

		<div class="books_drop">
			<div class="books_dropdown">

				<p class="dropD">{% trans 'Гуманитарные науки' %}</p>

				<ul class="books_dropdown-menu open">

					{% for category in categories %}
					<li><a href="{{category.get_absolute_url}}">{{category.name | capfirst}}</a></li>
					{% endfor %}
				</ul>
			</div>
		</div>
		<div class="books_drop">
			<div class="books_dropdown">
				<p class="dropD">{% trans 'Естественные науки' %}</p>
				<ul class="books_dropdown-menu open">
					{% for category in categories1 %}
					<li><a href="{{category.get_absolute_url}}">{{category.name | capfirst}}</a></li>
					{% endfor %}

				</ul>
			</div>
		</div>
		<div class="books_drop">
			<div class="books_dropdown">
				<p class="dropD">{% trans 'Технические науки' %}</p>
				<ul class="books_dropdown-menu open">
					{% for category in categories1 %}
					<li><a href="{{category.get_absolute_url}}">{{category.name | capfirst}}</a></li>
					{% endfor %}

				</ul>
			</div>
		</div>
	</div>
	<script>
		$(function () {
    const toggleMenu = function(menu) {
        menu.toggle();
    };

    const handleDropdownClick = function(event) {
        event.stopPropagation();
        const menu = $(this).find('.books_dropdown-menu');
        toggleMenu(menu);
    };

    const closeMenus = function() {
        const openMenus = $('.books_dropdown-menu:visible');
        openMenus.hide().removeData('clicked');
    };

    // Используем click для открытия и закрытия меню как на ПК, так и на мобильных устройствах
    $('.books_dropdown').on('click', function (event) {
        const menu = $(this).find('.books_dropdown-menu');
        if (menu.is(':visible')) {
            menu.hide();
        } else {
            closeMenus(); // Закрываем другие открытые меню
            toggleMenu(menu);
        }
    });

    $('.books_dropdown-menu').on('click', function (event) {
        event.stopPropagation();
        $(this).data('clicked', true);
    });

    $(document).on('click', function (e) {
        const target = $(e.target);
        if (!target.closest('.books_dropdown').length && !target.closest('.books_dropdown-menu').length) {
            closeMenus();
        }
    });

    if (window.innerWidth >= 768) {
        closeMenus();
    }
});


	</script>

	<div id="wrapper" style="padding-top: 60px;">




		<div data-hcolor="#f5550e"
			class="books_sam section section130 clip_none s_mode_s200 mobile_col2 inner_width img_square flex_fix transparent_ico"
			style="background-color:#fff;padding-top:80px;padding-bottom:80px;--tiles_radius:0px;--tiles_shadow:none;--bg_color:#fff;">
			<a name="a_4732122"></a>
			<div class="section_inner all_border btn_move"
				style="--icon_size:64px;--btn_fweight:300;--btn_fsize:18px;--item_title_fweight:400;">
				<div class="title"><b><span style="font-size:30px; color: #2c2c2c;">{% trans 'Книги' %}</span></b>
				</div>
				<div class="sub_title" style="font-size: 24px;">
					<div>{% trans 'Книга - великая вещь, пока человек умеет ею пользоваться!' %}<br></div>
				</div>
				<div class="books_box-only">
					<div class="books_search">
						<form action="{% url 'search' %}" method="GET" role="search">
							<div class="books_search-box">
								<input type="text" class="books_search-inp" placeholder="Искать книгу" name="q">
								<button class="books_search-btn" type="submit">поиск</button>
							</div>
						</form>
					</div>


				</div>

				<div class="catalog_items short_text count5 s200 ">

					{% for book in books %}
					<div class="arr1">
						<div class="col_4">
							<div data-link="" class="image1 s200 shadow">
								<img style="height: 230px;" data-lazy="1" loading="lazy" src="{{ book.photo.url }}">
							</div>
							<div class="title1">{{book.title}}</div>
							<div class="title1" style="font-size: 15px; margin: 0;">{{ book.author }}</div>
							<a class="btn1 surround  dark"
								style="background-color:#f5550e; border-radius: 10em; text-decoration: none; color: #fff;"
								href="{{book.pdf.url}}">{% trans 'Читать' %}
							</a>

						</div>
					</div>



					{% endfor %}

				</div>

			</div>
		</div>





	</div>



</body>

{% include 'footer.html' %}


{% endblock content %}


env
.\Scripts\activate 

templates/footer.html
<div class="section section303 text_right map_midi big_text" data-id="4722824" id="b_4722824"><a
    name="anchor8"></a>
<div class="map">
    <div class="map_inner">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d969.0454239923054!2d72.79612686109202!3d40.532326417438576!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38bdac04fccc99a9%3A0x408c6ca57e96bdb1!2z0JHQuNCx0LvQuNC-0YLQtdC60LAg0J7RiNCT0KM!5e0!3m2!1sru!2skg!4v1691053283317!5m2!1sru!2skg" width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
</div>
<div class="text text_block dark" style="background-color:#151515">
    <h2>Контактная информация:</h2>
    <div>
        <ul>
            <li>Кыргызстан, 723500, г. Ош, ул. Борубаева 2, ОшГУ</li>
            <li>E-mail: library@oshsu.kg</li>
            <li>Телефон: +996 3222 7-22-73</li>
            <li>Телефон факс: +996 3222 7-09-15</li>
            <li>Директор: М. А. Орозбаев </li>
        </ul>
        <p><br></p>
        <p><span style="font-size:18px"><span style="font-family:roboto">Время работы:
                    8:00-17:00&nbsp;</span></span></p>
    </div>
</div>
</div>

<div class="section section112" style="background-color:#f1f1f1;padding-top:30px;padding-bottom:30px"
data-id="4722825" id="b_4722825"><a name="a_4722825"></a>
<div class="section_inner width1170 hide_phone">
    <!-- <div class="logo_block">
        <div class="logo_img">
            <img data-lazy="1" src="./static/img/logo.png">
        </div>
    </div> -->
    <div class="menus_block">
        <div class="menu1 menu" style="color:#333">
            <div class="menu1_ul" style="font-size:14px;color:#333">
                <ul>
                    <li class="level0"><a href="https://www.oshsu.kg/ru"
                            title="Главный корпус Общий отдел: +996 3222 7-22-73, факс +996 3222 7-09-15, edu@oshsu.kg">Главный
                            корпус Общий отдел: +996 3222 7-22-73, факс +996 3222 7-09-15, edu@oshsu.kg</a>
                    </li>
                </ul>
            </div>
            <div class="menu_text1 menu_text">
                <p>© OSHSU. All rights reserved</p>
            </div>
         
        </div>
    </div>
    <div class="clear"></div>
</div>
</div>

templates/photo.html
{% extends 'index.html' %}
{% load static %}

{% load i18n %}
{% block content %}

{% include 'navbar.html' %}
<style>
	img {
		object-fit: contain;
	}
</style>

<body class="editor_false  lang_ru    not_ie">

	<div id="wrapper" style="padding-top: 88px;">
		<div data-autoslide="0" class="section section149 clip_none        mode_2  type_id_149"
			style="background-color:#fff;padding-top:80px;padding-bottom:80px;" id="b_5407562" data-id="5407562"><a
				name="a_5407562"></a>

			<div class="tools_left"><span class="left_btn" data-way="left"></span><span class="right_btn"
					data-way="right"></span></div>
			<div class="section_inner width1170 text_as_caption">
				<div class="title cke_editable cke_editable_inline cke_contents_ltr" data-editor-type="default"
					data-editor="text" data-name="title" contenteditable="false" spellcheck="false" tabindex="0"
					role="textbox">Фото</div>
				<div class="sub_title cke_editable cke_editable_inline cke_contents_ltr" data-editor-type="default"
					data-editor="text" data-name="sub_title" contenteditable="false" spellcheck="false" tabindex="0"
					role="textbox">{% trans 'Все находяшие фото' %}</div>

				<!-- <div class="arr1 " data-var-box="arr1" data-var-box-id="0">
					
					<div class="col_3">
						<div class="image1 " data-editor-type="default" data-editor="image" data-name="image1">

							<div style="width: 100%; margin: 0 auto;" id="carouselExampleIndicators"
								class="carousel slide" data-ride="carousel">
								<ol class="carousel-indicators">
									<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
									<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
									<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
								</ol>
								<div class="carousel-inner">
									<div class="carousel-item active">
										<img class="d-block w-100" src="{% static 'img/asus12.jpg' %}"
											alt="First slide">
									</div>
									<div class="carousel-item">
										<img class="d-block w-100" src="{% static 'img/asus12.jpg' %}"
											alt="Second slide">
									</div>
									<div class="carousel-item">
										<img class="d-block w-100" src="{% static 'img/asus12.jpg' %}"
											alt="Third slide">
									</div>
								</div>
								<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button"
									data-slide="prev">
									<span class="carousel-control-prev-icon" aria-hidden="true"></span>
									<span class="sr-only">Previous</span>
								</a>
								<a class="carousel-control-next" href="#carouselExampleIndicators" role="button"
									data-slide="next">
									<span class="carousel-control-next-icon" aria-hidden="true"></span>
									<span class="sr-only">Next</span>
								</a>

							</div>
						</div>
						
					</div>

					<div class="col_3">
						<div class="image1 " data-editor-type="default" data-editor="image" data-name="image1">

							<div style="width: 100%; margin: 0 auto;" id="carouselExampleIndicators"
								class="carousel slide" data-ride="carousel">
								<ol class="carousel-indicators">
									<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
									<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
									<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
								</ol>
								<div class="carousel-inner">
									<div class="carousel-item active">
										<img class="d-block w-100" src="{% static 'img/asus12.jpg' %}"
											alt="First slide">
									</div>
									<div class="carousel-item">
										<img class="d-block w-100" src="{% static 'img/asus12.jpg' %}"
											alt="Second slide">
									</div>
									<div class="carousel-item">
										<img class="d-block w-100" src="{% static 'img/asus12.jpg' %}"
											alt="Third slide">
									</div>
								</div>
								<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button"
									data-slide="prev">
									<span class="carousel-control-prev-icon" aria-hidden="true"></span>
									<span class="sr-only">Previous</span>
								</a>
								<a class="carousel-control-next" href="#carouselExampleIndicators" role="button"
									data-slide="next">
									<span class="carousel-control-next-icon" aria-hidden="true"></span>
									<span class="sr-only">Next</span>
								</a>

							</div>
						</div>
						
					</div>

					<div class="col_3">
						<div class="image1 " data-editor-type="default" data-editor="image" data-name="image1">

							<div style="width: 100%; margin: 0 auto;" id="carouselExampleIndicators"
								class="carousel slide" data-ride="carousel">
								<ol class="carousel-indicators">
									<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
									<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
									<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
								</ol>
								<div class="carousel-inner">
									<div class="carousel-item active">
										<img class="d-block w-100" src="{% static 'img/asus12.jpg' %}"
											alt="First slide">
									</div>
									<div class="carousel-item">
										<img class="d-block w-100" src="{% static 'img/asus12.jpg' %}"
											alt="Second slide">
									</div>
									<div class="carousel-item">
										<img class="d-block w-100" src="{% static 'img/asus12.jpg' %}"
											alt="Third slide">
									</div>
								</div>
								<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button"
									data-slide="prev">
									<span class="carousel-control-prev-icon" aria-hidden="true"></span>
									<span class="sr-only">Previous</span>
								</a>
								<a class="carousel-control-next" href="#carouselExampleIndicators" role="button"
									data-slide="next">
									<span class="carousel-control-next-icon" aria-hidden="true"></span>
									<span class="sr-only">Next</span>
								</a>

							</div>
						</div>
						
					</div>



				</div> -->

				<div class="container">
					<div class=" w-100 mt-4">
						<div class="d-flex flex-wrap justify-content-between">
							<!-- Product Cart Start -->
							{% for i in photos %}
							<div class="card border border-0 shadow-sm d-inline-block m-1 mt-3" style="width: 16.5rem;">
								{% if i.postimage_set.exists %}
								<a href="{% url 'photo_detail' i.id %}"><img height="200" class=" card-img-top"
										src="{{i.postimage_set.all.first.image.url}}" alt=""></a>
								{% else %}
								<img height="200" class=" card-img-top" src="images/14pro2.jfif" alt="">
								{% endif %}
								<div class="card-body">
									<h6 class="align-center card-title">{{i.title}}</h6>

									<div class="buttons d-flex flex-wrap justify-content-between ">

									</div>
								</div>
							</div>
							{% endfor %}
							<!-- Product Cart End -->

						</div>
					</div>
				</div>
			</div>
		</div>

	</div>

</body>
{% include 'footer.html' %}

{% endblock content %}

templates/single_photo.html
{% extends 'index.html' %}
{% load static %}

{% block content %}

{% include 'navbar.html' %}

<style>
	img {
		object-fit: contain;
	}
</style>

<body class="editor_false  lang_ru    not_ie">

	<div id="wrapper" style="padding-top: 88px;">
		<div data-autoslide="0" class="section section149 clip_none        mode_2  type_id_149"
			style="background-color:#fff;padding-top:80px;padding-bottom:80px;" id="b_5407562" data-id="5407562"><a
				name="a_5407562"></a>

			<div class="tools_left"><span class="left_btn" data-way="left"></span><span class="right_btn"
					data-way="right"></span></div>
			<div class="section_inner width1170 text_as_caption">
				<div class="title cke_editable cke_editable_inline cke_contents_ltr" data-editor-type="default"
					data-editor="text" data-name="title" contenteditable="false" spellcheck="false" tabindex="0"
					role="textbox">{% trans 'Фото' %}</div>
				
				<div class="arr1 " data-var-box="arr1" data-var-box-id="0">

					<div style="width: 40%; margin: 0 auto;" id="carouselExampleIndicators" class="carousel slide"
						data-ride="carousel">
						<ol class="carousel-indicators">
							<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
							<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
						</ol>
						<div class="carousel-inner">
							{% for i in photo.postimage_set.all %}
							{% if i == photo.postimage_set.first %}
							<div class="carousel-item active">
								<img class="d-block w-100" style="height: 500px; object-fit: contain;"
									src="{{i.image.url}}" alt="First slide">
							</div>
							{% else %}

							<div class="carousel-item">
								<img class="d-block w-100" style="height: 500px;  object-fit: contain;"
									src="{{i.image.url}}" alt="Second slide">
							</div>
							{% endif %}
							{% endfor %}

						</div>
						<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button"
							data-slide="prev">
							<span class="carousel-control-prev-icon" aria-hidden="true"></span>
							<span class="sr-only">Previous</span>
						</a>
						<a class="carousel-control-next" href="#carouselExampleIndicators" role="button"
							data-slide="next">
							<span class="carousel-control-next-icon" aria-hidden="true"></span>
							<span class="sr-only">Next</span>
						</a>
					</div>

                {% comment %}
					<!-- <div class="container">
						<div class=" w-100 mt-5 ">
							<div class="row shadow-sm ">
								<div class="col-4 p-3">
									<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
										<div class="carousel-inner">

											<div class="carousel-item active thumbnail shadow-sm ">
												<img class="d-block w-100 " width="400" height="270"
													src="{{i.image.url}}" alt="">
											</div>
											<div class="carousel-item thumbnail shadow-sm">
												<img class="d-block w-100  " width="400" height="270"
													src="{{i.image.url}}" alt="">
											</div>

										</div>
										<button class="carousel-control-prev" type="button"
											data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
											<span class="carousel-control-prev-icon" aria-hidden="true"></span>
											<span class="visually-hidden">Previous</span>
										</button>
										<button class="carousel-control-next" type="button"
											data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
											<span class="carousel-control-next-icon" aria-hidden="true"></span>
											<span class="visually-hidden">Next</span>
										</button>
									</div>
								</div>

							</div>

						</div>
					</div> -->
					<!-- Product Detail End -->
					{% endcomment %}

				</div>
			</div>

		</div>

</body>
{% include 'footer.html' %}

{% endblock content %}